# SPDX-License-Identifier: FSL-1.1-MIT
"""Генератор ~/.local/bin/mnemo — лаунчер Claude Code с деградацией по трактам.

Порядок выбора при каждом запуске:

1. **passthrough-прокси mnemostroma жив** → ``ANTHROPIC_BASE_URL`` на него,
   работает Observer-capture;
2. **api.anthropic.com достижим** → прямое подключение без записи;
3. **есть OPENMODEL_API_KEY** → запасной провайдер openmodel
   (Anthropic Messages API на своём хосте).

Ограничение, которое нельзя обойти обёрткой: выбор делается один раз, при
старте процесса. Настройка ``fallbackModel`` в Claude Code переключает модели
на лету, но только в пределах одного endpoint'а и одной авторизации — сменить
на openmodel она не может, там другой хост и другой ключ.
"""
from __future__ import annotations

from pathlib import Path

# Хост запасного провайдера отдаёт Anthropic Messages API, поэтому Claude Code
# работает с ним через штатный ANTHROPIC_BASE_URL без каких-либо адаптеров.
FALLBACK_BASE_URL = "https://api.openmodel.ai"
FALLBACK_MODEL = "deepseek-v4-flash"
FALLBACK_KEY_ENV = "OPENMODEL_API_KEY"

# Ключ живёт в ~/.hermes/.env и в обычный шелл не экспортируется — без чтения
# из файла третья ступень не срабатывала бы никогда.
FALLBACK_KEY_FILE = "$HOME/.hermes/.env"

# Хосты Claude Code, которые всегда идут напрямую, минуя HTTPS_PROXY. Без этого
# глобально экспортированный HTTPS_PROXY (MITM на 8764) перехватывал бы и их —
# при выключенной mnemostroma это оборачивается Connection error на пустом месте.
_DIRECT_HOSTS = "api.anthropic.com,console.anthropic.com,statsig.anthropic.com"


def write_claude_wrapper(
    wrapper_path: Path,
    ca_cert: Path,
    port: int = 8767,
    probe_timeout: int = 3,
    anthropic_host: str = "api.anthropic.com",
) -> None:
    wrapper_path.parent.mkdir(parents=True, exist_ok=True)
    wrapper_path.write_text(
        f"""#!/bin/bash
# Generated by `mnemostroma setup` — do not edit, re-run setup instead.
CLAUDE_BIN=$(command -v claude 2>/dev/null)
if [ -z "$CLAUDE_BIN" ]; then
  echo "mnemo: claude not found in PATH" >&2
  exit 1
fi

# Проба TCP-порта. Открываем и сразу закрываем дескриптор: `echo > /dev/tcp/...`
# писал бы перевод строки в сокет, то есть слал прокси мусорный запрос на
# каждый запуск. `timeout` обязателен — без него зависший порт вешает лаунчер.
probe() {{
  timeout {probe_timeout} bash -c "exec 3<>/dev/tcp/$1/$2" 2>/dev/null
}}

MNEMO_ENV=()
MNEMO_UNSET=()

# Ключ запасного провайдера: из окружения, иначе из файла Hermes. Значение
# нигде не печатается и не попадает в командную строку.
if [ -z "${{{FALLBACK_KEY_ENV}}}" ] && [ -r "{FALLBACK_KEY_FILE}" ]; then
  {FALLBACK_KEY_ENV}=$(sed -n "s/^{FALLBACK_KEY_ENV}=//p" "{FALLBACK_KEY_FILE}" | tail -1)
fi
# Прямые хосты не должны уходить в MITM-прокси, даже если HTTPS_PROXY
# экспортирован глобально.
if [ -n "$NO_PROXY" ]; then
  MNEMO_ENV+=("NO_PROXY=$NO_PROXY,{_DIRECT_HOSTS}")
else
  MNEMO_ENV+=("NO_PROXY={_DIRECT_HOSTS}")
fi

if probe 127.0.0.1 {port}; then
  # 1. mnemostroma на связи — пишем сессию через passthrough-прокси.
  MNEMO_ENV+=("ANTHROPIC_BASE_URL=https://127.0.0.1:{port}")
  MNEMO_ENV+=("NODE_EXTRA_CA_CERTS={ca_cert}")
elif probe {anthropic_host} 443; then
  # 2. Прокси нет, но Anthropic доступен — идём напрямую, без записи.
  # ANTHROPIC_BASE_URL снимается явно: унаследованное из окружения значение
  # (прошлый запуск, экспорт в .profile) продолжало бы указывать на мёртвый
  # прокси, и «фолбэк» молча упирался бы в connection refused.
  # NODE_EXTRA_CA_CERTS, наоборот, оставляем: он ДОБАВЛЯЕТ доверие к CA, а не
  # подменяет системные корни — в отличие от SSL_CERT_FILE у Python.
  MNEMO_UNSET+=(-u ANTHROPIC_BASE_URL)
  echo "mnemo: mnemostroma proxy is down — direct connection, no capture" >&2
elif [ -n "${{{FALLBACK_KEY_ENV}}}" ]; then
  # 3. Anthropic недостижим — запасной провайдер.
  echo "mnemo: {anthropic_host} unreachable — falling back to {FALLBACK_BASE_URL} ({FALLBACK_MODEL})" >&2
  MNEMO_ENV+=("ANTHROPIC_BASE_URL={FALLBACK_BASE_URL}")
  MNEMO_ENV+=("ANTHROPIC_MODEL={FALLBACK_MODEL}")
  # x-api-key, а не Authorization: Bearer. openmodel не входит в список
  # Bearer-провайдеров Hermes (_requires_bearer_auth: MiniMax/Azure/Palantir/
  # Nous), а opencode ходит туда через @ai-sdk/anthropic, который шлёт
  # x-api-key. Оба рабочих тракта сходятся на этом заголовке.
  # export, а не env-массив: `env KEY=... cmd` кладёт секрет в argv, где его
  # видно в `ps` любому пользователю. exec ниже всё равно заменяет процесс,
  # так что утечки в вызывающий шелл не будет даже при `source`.
  export ANTHROPIC_API_KEY="${{{FALLBACK_KEY_ENV}}}"
  MNEMO_UNSET+=(-u ANTHROPIC_AUTH_TOKEN)
else
  echo "mnemo: {anthropic_host} unreachable and {FALLBACK_KEY_ENV} is not set" >&2
  MNEMO_UNSET+=(-u ANTHROPIC_BASE_URL)
fi

# env-scoped к этому exec: если скрипт когда-нибудь `source`-нут вместо
# запуска, export/unset утекли бы в вызывающий шелл на всю его жизнь и
# сломали TLS посторонним инструментам.
#
# SSL_CERT_FILE/CURL_CA_BUNDLE/REQUESTS_CA_BUNDLE снимаем принудительно: если
# в окружении висит глобальный MITM-CA (единственный корень), Claude Code
# доверяет только ему и падает с "invalid peer certificate: UnknownIssuer"
# на любом прямом хосте. Claude Code ходит через NODE_EXTRA_CA_CERTS, а он
# ДОБАВЛЯЕТ доверие, а не заменяет системные корни.
exec env "${{MNEMO_UNSET[@]}}" -u SSL_CERT_FILE -u CURL_CA_BUNDLE -u REQUESTS_CA_BUNDLE "${{MNEMO_ENV[@]}}" "$CLAUDE_BIN" "$@"
""",
        encoding="utf-8",
    )
    wrapper_path.chmod(0o755)
