# SPDX-License-Identifier: FSL-1.1-MIT
"""Generate ~/.local/bin/mnemo-opencode — a drop-in opencode launcher that
routes traffic through the local MITM proxy when Mnemostroma is running,
and falls back to a direct connection (no recording) otherwise.
"""
from __future__ import annotations

from pathlib import Path


def write_opencode_wrapper(wrapper_path: Path, ca_cert: Path, port: int) -> None:
    wrapper_path.parent.mkdir(parents=True, exist_ok=True)
    wrapper_path.write_text(
        f"""#!/bin/bash
# Generated by `mnemostroma setup` — do not edit, re-run setup instead.
OPENCODE_BIN=$(command -v opencode 2>/dev/null)
if [ -z "$OPENCODE_BIN" ]; then
  echo "mnemo: opencode not found in PATH" >&2
  exit 1
fi
MNEMO_ENV=()
if echo > /dev/tcp/127.0.0.1/{port} 2>/dev/null; then
  MNEMO_ENV=(HTTPS_PROXY=http://127.0.0.1:{port} NODE_EXTRA_CA_CERTS={ca_cert})
fi
# env-scoped to this exec only: if this script is ever `source`d instead of
# executed, `export`/`unset` would leak the MITM proxy and CA into the
# calling shell for its whole lifetime, breaking unrelated tools' TLS.
# ANTHROPIC_BASE_URL conflicts with MITM for non-Anthropic providers.
exec env -u ANTHROPIC_BASE_URL "${{MNEMO_ENV[@]}}" "$OPENCODE_BIN" "$@"
""",
        encoding="utf-8",
    )
    wrapper_path.chmod(0o755)
