#!/usr/bin/env bash
# ─────────────────────────────────────────────────────────────────────
# install-daemon.sh (universal)
# Usage:
#   bash scripts/install-daemon.sh [--local]
#   bash <(curl -fsSL https://raw.githubusercontent.com/GG-QandV/mnemostroma/main/scripts/install-daemon.sh)
# ─────────────────────────────────────────────────────────────────────
set -euo pipefail

# 0. Detect Mode
INSTALL_MODE="github"
if [[ "${1:-}" == "--local" ]]; then
    INSTALL_MODE="local"
    echo "⚡ Local editable mode enabled."
fi

# 1. Verify Python 3.12+
PYTHON_BIN=""
for candidate in python3.12 python3.13 python3 python; do
    if command -v "$candidate" &>/dev/null; then
        ver=$("$candidate" -c "import sys; print(sys.version_info >= (3,12))" 2>/dev/null || echo False)
        if [ "$ver" = "True" ]; then
            PYTHON_BIN="$candidate"
            break
        fi
    fi
done

if [ -z "$PYTHON_BIN" ]; then
    echo "❌ Python 3.12+ required."
    exit 1
fi

PYTHON_VER=$("$PYTHON_BIN" -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")
echo "✅ Python $PYTHON_VER found."

# 2. Setup VENV
VENV_DIR="$HOME/.mnemostroma/venv"
mkdir -p "$HOME/.mnemostroma"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(dirname "$SCRIPT_DIR")"

if [ ! -f "$VENV_DIR/bin/python3" ]; then
    "$PYTHON_BIN" -m venv "$VENV_DIR"
fi

if [ "$INSTALL_MODE" == "local" ]; then
    echo "Installing from local source..."
    "$VENV_DIR/bin/pip" install -e "$REPO_ROOT[all]"
else
    # R-09: Detect editable install — preserve it, do not overwrite with static GitHub copy
    IS_EDITABLE=$("$VENV_DIR/bin/pip" show -f mnemostroma 2>/dev/null | grep -c "Editable project location" || true)
    if [ "$IS_EDITABLE" -gt 0 ]; then
        echo "⚡ Editable install detected — skipping GitHub install to preserve local source link."
        echo "   To force GitHub install: remove --local flag and uninstall first."
    else
        echo "Installing from GitHub..."
        "$VENV_DIR/bin/pip" install --quiet --upgrade "mnemostroma[all] @ git+https://github.com/GG-QandV/mnemostroma.git"
    fi
fi

# 2.1 Verify CLI is available before proceeding
if ! command -v "$VENV_DIR/bin/mnemostroma" &>/dev/null; then
    echo "❌ mnemostroma CLI not found after install. Aborting."
    exit 1
fi

# 2.5 Download models (Phase 5: || {} guard — failure is a warning, not fatal)
echo "Downloading models..."
"$VENV_DIR/bin/mnemostroma" install-models || {
    echo "⚠ Model download failed or already up to date."
    echo "  Run manually after install: mnemostroma install-models"
}

# 3. Clean Zombies
echo "Ensuring clean state..."
if [ -f "$SCRIPT_DIR/clean-zombies.py" ]; then
    "$VENV_DIR/bin/python" "$SCRIPT_DIR/clean-zombies.py" || echo "Warning: clean-zombies failed"
else
    "$VENV_DIR/bin/mnemostroma" cleanup --silent || true
fi

# 4. Install systemd/launchd service units (R-02: guard — failure is fatal, not silent)
"$VENV_DIR/bin/mnemostroma" service install || {
    echo "❌ Service install failed. Check output above."
    echo "   Run manually: mnemostroma service install"
    exit 1
}

# 5. Smart Aliases (Phase 4: $HOME-relative paths — safe in curl-pipe mode)
SHELL_RC="$HOME/.bashrc"
[ -f "$HOME/.zshrc" ] && SHELL_RC="$HOME/.zshrc"

# Install mnemo-health.sh to stable location (independent of $SCRIPT_DIR)
MNEMO_SCRIPTS_DIR="$HOME/.mnemostroma/scripts"
mkdir -p "$MNEMO_SCRIPTS_DIR"

if [ -f "$SCRIPT_DIR/mnemo-health.sh" ]; then
    # Local install: copy from repo
    cp "$SCRIPT_DIR/mnemo-health.sh" "$MNEMO_SCRIPTS_DIR/mnemo-health.sh"
    chmod +x "$MNEMO_SCRIPTS_DIR/mnemo-health.sh"
else
    # curl-pipe install: write minimal health check inline
    cat > "$MNEMO_SCRIPTS_DIR/mnemo-health.sh" << 'HEALTH_EOF'
#!/usr/bin/env bash
# Mnemostroma health check (auto-generated by install-daemon.sh)
VENV="$HOME/.mnemostroma/venv/bin/mnemostroma"
if [ ! -f "$VENV" ]; then echo "❌ mnemostroma not installed"; exit 1; fi
"$VENV" status
HEALTH_EOF
    chmod +x "$MNEMO_SCRIPTS_DIR/mnemo-health.sh"
fi

GUARD_BLOCK_START="# MNEMOSTROMA_START"
GUARD_BLOCK_END="# MNEMOSTROMA_END"

# Remove old block
if grep -q "$GUARD_BLOCK_START" "$SHELL_RC"; then
    sed -i "/$GUARD_BLOCK_START/,/$GUARD_BLOCK_END/d" "$SHELL_RC"
fi

# Add new block — all paths are $HOME-relative, stable across install methods
cat >> "$SHELL_RC" << EOF

$GUARD_BLOCK_START
alias mnemo-health="$MNEMO_SCRIPTS_DIR/mnemo-health.sh"
alias mnemo-restart="systemctl --user restart mnemostroma-daemon.service mnemostroma-proxy.service mnemostroma-watchdog.service && sleep 3 && mnemostroma status"
alias mnemo-logs="journalctl --user -u mnemostroma-daemon.service -f"
$GUARD_BLOCK_END
EOF

# Detect installed version dynamically
VERSION=$("$VENV_DIR/bin/python" -c "import mnemostroma; print(mnemostroma.__version__)" 2>/dev/null || echo "2.1.5")

echo "🎉 Mnemostroma v${VERSION} Beta successfully installed!"
echo "Installation finalized. Reload shell: source $SHELL_RC"
echo ""
echo "📢 IMPORTANT NEXT STEP:"
echo "To capture chat sessions from Claude, Perplexity, ChatGPT, Gemini, etc. into Mnemostroma,"
echo "you MUST load the Mnemostroma browser extension into your browser."
echo "Read the easy setup guide:"
echo "👉 src/extension/docs/INSTALL.md"
echo ""
